# Generated by Django 4.1.7 on 2023-03-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=32)),
                ('company_introduction', models.TextField()),
                ('logo', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='LeakRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ManageUserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
                ('entry_data', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.department')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RewardLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RewardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SkillRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
                ('diploma', models.CharField(max_length=32)),
                ('occupation', models.CharField(max_length=32)),
                ('introduce', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=254)),
                ('company_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.companyinformation')),
                ('create_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.manageuserdetail')),
                ('user_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=32)),
                ('project_name', models.CharField(max_length=32)),
                ('project_details', models.TextField()),
                ('create_data', models.DateField()),
                ('start_data', models.DateField()),
                ('end_data', models.DateField()),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.businesstype')),
                ('company_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.companyinformation')),
                ('industry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.industrytype')),
                ('project_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.projectstatus')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.projecttype')),
                ('reward_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.rewardlevel')),
                ('reward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.rewardtype')),
                ('skill_requirements', models.ManyToManyField(to='srcmodel.skillrequirements')),
            ],
        ),
        migrations.CreateModel(
            name='LeakInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leak_id', models.CharField(max_length=32)),
                ('leak_name', models.CharField(max_length=32)),
                ('leak_describe', models.TextField()),
                ('leak_scope', models.CharField(max_length=32)),
                ('leak_harm', models.CharField(max_length=64)),
                ('repair_comments', models.CharField(max_length=64)),
                ('leak_status', models.CharField(max_length=32)),
                ('leak_reward', models.IntegerField()),
                ('create_data', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.user')),
                ('leak_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.leakrank')),
            ],
        ),
    ]
