# Generated by Django 4.1.7 on 2023-03-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '业务类型表',
                'verbose_name_plural': '业务类型表',
            },
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=32, verbose_name='公司名称')),
                ('company_title', models.CharField(max_length=64, verbose_name='公司简介')),
                ('company_introduction', models.TextField(verbose_name='公司描述')),
                ('logo', models.CharField(max_length=128, verbose_name='logo')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
                ('website', models.URLField(verbose_name='网站链接')),
            ],
            options={
                'verbose_name': '公司信息表',
                'verbose_name_plural': '公司信息表',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=32, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '部门表',
                'verbose_name_plural': '部门表',
            },
        ),
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '行业类型表',
                'verbose_name_plural': '行业类型表',
            },
        ),
        migrations.CreateModel(
            name='LeakRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=16, verbose_name='等级')),
            ],
            options={
                'verbose_name': '漏洞等级表',
                'verbose_name_plural': '漏洞等级表',
            },
        ),
        migrations.CreateModel(
            name='ManageUserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')], verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('entry_data', models.DateField(verbose_name='入职时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '运营用户信息表',
                'verbose_name_plural': '运营用户信息表',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=16, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '项目状态表',
                'verbose_name_plural': '项目状态表',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '项目类型表',
                'verbose_name_plural': '项目类型表',
            },
        ),
        migrations.CreateModel(
            name='RewardLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=16, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '奖励等级表',
                'verbose_name_plural': '奖励等级表',
            },
        ),
        migrations.CreateModel(
            name='RewardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '奖励类型表',
                'verbose_name_plural': '奖励类型表',
            },
        ),
        migrations.CreateModel(
            name='SkillRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '技能要求表',
                'verbose_name_plural': '技能要求表',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')], verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('diploma', models.CharField(max_length=32, verbose_name='学历')),
                ('occupation', models.CharField(max_length=32, verbose_name='职业')),
                ('introduce', models.CharField(max_length=254, verbose_name='简介')),
            ],
            options={
                'verbose_name': '安全人员信息表',
                'verbose_name_plural': '安全人员信息表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=32, verbose_name='联系电话')),
                ('password', models.CharField(max_length=512, verbose_name='认证密码')),
                ('usertype', models.SmallIntegerField(choices=[(0, '安全人员'), (1, '企业人员'), (2, '运营人员')], verbose_name='用户类型')),
                ('company_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srcmodel.companyinformation', verbose_name='企业信息')),
                ('manage_userinfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srcmodel.manageuserdetail', verbose_name='运营用户信息')),
                ('user_detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srcmodel.userdetail', verbose_name='测试用户信息')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=32, verbose_name='项目编号')),
                ('project_name', models.CharField(max_length=32, verbose_name='项目名称')),
                ('project_details', models.TextField(verbose_name='项目详情')),
                ('create_data', models.DateField(verbose_name='创建时间')),
                ('start_data', models.DateField(verbose_name='项目开始时间')),
                ('end_data', models.DateField(verbose_name='项目结束时间')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.businesstype', verbose_name='业务类型')),
                ('company_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.companyinformation', verbose_name='所属公司')),
                ('industry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.industrytype', verbose_name='行业类型')),
                ('project_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.projectstatus', verbose_name='项目状态')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.projecttype', verbose_name='项目类型')),
                ('reward_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.rewardlevel', verbose_name='奖金等级')),
                ('reward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.rewardtype', verbose_name='奖励类型')),
                ('skill_requirements', models.ManyToManyField(to='srcmodel.skillrequirements', verbose_name='技能要求')),
            ],
            options={
                'verbose_name': '项目信息表',
                'verbose_name_plural': '项目信息表',
            },
        ),
        migrations.CreateModel(
            name='LeakInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leak_id', models.CharField(max_length=32, verbose_name='漏洞编号')),
                ('leak_name', models.CharField(max_length=32, verbose_name='漏洞名称')),
                ('leak_describe', models.TextField(verbose_name='漏洞描述')),
                ('leak_scope', models.CharField(max_length=32, verbose_name='影响范围')),
                ('leak_harm', models.CharField(max_length=64, verbose_name='漏洞危害')),
                ('repair_comments', models.CharField(max_length=64, verbose_name='整改意见')),
                ('leak_status', models.CharField(max_length=32, verbose_name='漏洞状态')),
                ('leak_reward', models.IntegerField(verbose_name='漏洞奖励')),
                ('create_data', models.DateField(verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.user', verbose_name='提交人')),
                ('leak_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.leakrank', verbose_name='漏洞等级')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '漏洞信息表',
                'verbose_name_plural': '漏洞信息表',
            },
        ),
    ]
