# Generated by Django 4.1.7 on 2023-03-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcmodel', '0002_leakinformation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstype',
            name='type_name',
            field=models.CharField(max_length=32, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='address',
            field=models.CharField(max_length=32, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='company_introduction',
            field=models.TextField(verbose_name='公司描述'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='company_name',
            field=models.CharField(max_length=32, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='company_title',
            field=models.CharField(max_length=64, verbose_name='公司简介'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='logo',
            field=models.CharField(max_length=128, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='website',
            field=models.URLField(verbose_name='网站链接'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(max_length=32, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='industrytype',
            name='type_name',
            field=models.CharField(max_length=32, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.user', verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='create_data',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='leak_describe',
            field=models.TextField(verbose_name='漏洞描述'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='leak_harm',
            field=models.CharField(max_length=64, verbose_name='漏洞危害'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='leak_id',
            field=models.CharField(max_length=32, verbose_name='漏洞编号'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='leak_name',
            field=models.CharField(max_length=32, verbose_name='漏洞名称'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='leak_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.leakrank', verbose_name='漏洞等级'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='leak_reward',
            field=models.IntegerField(verbose_name='漏洞奖励'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='leak_scope',
            field=models.CharField(max_length=32, verbose_name='影响范围'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='leak_status',
            field=models.CharField(max_length=32, verbose_name='漏洞状态'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='leakinformation',
            name='repair_comments',
            field=models.CharField(max_length=64, verbose_name='整改意见'),
        ),
        migrations.AlterField(
            model_name='leakrank',
            name='level_name',
            field=models.CharField(max_length=16, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='manageuserdetail',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='manageuserdetail',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='manageuserdetail',
            name='entry_data',
            field=models.DateField(verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='manageuserdetail',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='manageuserdetail',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='project',
            name='business_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.businesstype', verbose_name='业务类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.companyinformation', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_data',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_data',
            field=models.DateField(verbose_name='项目结束时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.industrytype', verbose_name='行业类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_details',
            field=models.TextField(verbose_name='项目详情'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=32, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=32, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.projectstatus', verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.projecttype', verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reward_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.rewardlevel', verbose_name='奖金等级'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.rewardtype', verbose_name='奖励类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skill_requirements',
            field=models.ManyToManyField(to='srcmodel.skillrequirements', verbose_name='技能要求'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_data',
            field=models.DateField(verbose_name='项目开始时间'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='type_name',
            field=models.CharField(max_length=16, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='type_name',
            field=models.CharField(max_length=32, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='rewardlevel',
            name='level_name',
            field=models.CharField(max_length=16, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='rewardtype',
            name='type_name',
            field=models.CharField(max_length=32, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='skillrequirements',
            name='type_name',
            field=models.CharField(max_length=32, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.companyinformation', verbose_name='企业信息'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.manageuserdetail', verbose_name='运营用户信息'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=254, verbose_name='认证密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='srcmodel.userdetail', verbose_name='测试用户信息'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(max_length=16, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='diploma',
            field=models.CharField(max_length=32, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='introduce',
            field=models.CharField(max_length=254, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='occupation',
            field=models.CharField(max_length=32, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')], verbose_name='性别'),
        ),
    ]
