# Generated by Django 4.1.7 on 2023-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcmodel', '0004_alter_businesstype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.SmallIntegerField(choices=[(0, '安全人员'), (1, '企业人员'), (2, '运营人员')], verbose_name='用户类型'),
        ),
    ]
