# Generated by Django 4.1.7 on 2023-03-14 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcmodel', '0005_alter_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_name',
            new_name='manage_userinfo',
        ),
    ]
