# Generated by Django 4.1.7 on 2023-03-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcmodel', '0006_rename_create_name_user_manage_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(verbose_name='认证密码'),
        ),
    ]
