# Generated by Django 4.1.7 on 2023-03-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcmodel', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=512, verbose_name='认证密码'),
        ),
    ]
